version: '3.8'

services:
  postgres: 
    user: root
    image: postgres:latest
    environment:
      POSTGRES_USER: local
      POSTGRES_PASSWORD: POSTGRES_PASSWORD
      POSTGRES_DB: local
      PGDATA: '/var/lib/pg_data'
    ports:
      - '5433:5432'
    networks:
      - local
networks:
  local:
      